<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.chenile</groupId>
    <artifactId>chenile-security-parent</artifactId>
    <version>${revision}</version>
    <name>Chenile Security Parent</name>

    <modules>
        <module>legacy-security/chenile-security-api</module>
        <module>legacy-security/chenile-security</module>
        <module>legacy-security/security-interceptor</module>
        <module>legacy-security/cucumber-sec-utils</module>
        <module>auth-framework/core</module>
        <module>auth-framework/starters/resource-server</module>
        <module>auth-framework/starters/gateway</module>
        <module>auth-framework/starters/auth-server</module>
        <module>auth-framework/auth-server</module>
        <module>auth-framework/gateway</module>
    </modules>

    <packaging>pom</packaging>

    <parent>
        <groupId>org.chenile</groupId>
        <artifactId>chenile-parent</artifactId>
        <version>2.1.29</version>
    </parent>

    <properties>
        <revision>${chenile.security.version}</revision>
        <spring-cloud.version>2025.1.2</spring-cloud.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <licenses>
        <license>
            <name>MIT License</name>
            <url>http://www.opensource.org/licenses/mit-license.php</url>
        </license>
    </licenses>


    <distributionManagement>
        <site>
            <id>website</id>
            <url>http://chenile.org</url>
        </site>
    </distributionManagement>

</project>
